apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helloworld-pvc
  namespace: viktorgt
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi